---
# ----------------------------------------------------------------------------------------------
# Script Name: remove-database.yml
# Version: 1.0
# Author: Eric Lacroix
# Date: 24/10/2023
#
# Description: Remove database resources in OpenShift.
#
# ----------------------------------------------------------------------------------------------

- name: Remove database resources
  hosts: controlnode
  connection: local
  tasks:
    # Remove database deployment from cluster
    - name: Remove database deployment from cluster
      ansible.builtin.command: 'oc delete -f ../database/deployment/data-deployment-v1.0.yml'
      register: data_deployment_info
    - debug: 
        msg: "{{data_deployment_info}}"
    
    # Remove database persistent volume claim from cluster
    - name: Remove database persistent volume claim from cluster
      ansible.builtin.command: 'oc delete -f ../database/deployment/data-pvc.yml'
      register: data_pvc_info
    - debug: 
        msg: "{{data_pvc_info}}"

    # Remove local images
    - name: Remove all local images
      ansible.builtin.command: 'podman rmi --all'
      register: local_image_info
    - debug: 
        msg: "{{local_image_info}}"