---
# ----------------------------------------------------------------------------------------------
# Script Name: scale-database.yml
# Version: 1.0
# Author: Eric Lacroix
# Date: 24/10/2023
#
# Description: Scale database deployment.
#
# ----------------------------------------------------------------------------------------------

- name: Scale database deployment
  hosts: controlnode
  connection: local
  tasks:
    - name: Scale database deployment
      ansible.builtin.command: 'oc scale deployment {{data_deployment}} --replicas={{replica}}'
      register: scale_data_deployment_info
    - debug: 
        msg: "{{scale_data_deployment_info}}"