---
# ----------------------------------------------------------------------------------------------
# Script Name: stop-bookmark.yml
# Version: 1.0
# Author: Eric Lacroix
# Date: 24/10/2023
#
# Description: Stop Bookmark resources in OpenShift.
#
# ----------------------------------------------------------------------------------------------

- name: Stop Bookmark resources
  hosts: controlnode
  connection: local
  tasks:
    # Stop web deployment
    - name: Stop web deployment
      ansible.builtin.command: 'oc scale deployment {{web_deployment}} --replicas=0'
      register: scale_web_deployment_info
    - debug: 
        msg: "{{scale_web_deployment_info}}"
    
    # Stop application deployment
    - name: Stop application deployment
      ansible.builtin.command: 'oc scale deployment {{app_deployment}} --replicas=0'
      register: scale_app_deployment_info
    - debug: 
        msg: "{{scale_app_deployment_info}}"
    
    # Stop database deployment
    - name: Stop database deployment
      ansible.builtin.command: 'oc scale deployment {{data_deployment}} --replicas=0'
      register: scale_data_deployment_info
    - debug: 
        msg: "{{scale_data_deployment_info}}"
    
    