---
# ----------------------------------------------------------------------------------------------
# Script Name: update-application.yml
# Version: 1.0
# Author: Eric Lacroix
# Date: 24/10/2023
#
# Description: Update application from image.
#
# ----------------------------------------------------------------------------------------------

- name: Update application from image
  hosts: controlnode
  connection: local
  tasks:
    # Remove application deployment from cluster
    - name: Remove application deployment from cluster
      ansible.builtin.command: 'oc delete -f ../application/deployment/app-deployment-v1.0.yml'
      register: app_deployment_info
    - debug: 
        msg: "{{app_deployment_info}}"
    
    # Remove local images
    - name: Remove all local images
      ansible.builtin.command: 'podman rmi --all'
      register: local_image_info
    - debug: 
        msg: "{{local_image_info}}"

    # Deploy the application
    - name: Deploy application from image
      ansible.builtin.shell: 'oc create -f ../application/deployment/{{app_deployment_file}}'
      args:
        executable: /bin/bash
      register: app_build_info
    - debug: 
        msg: "{{app_build_info}}"
    
    # Stop web deployment
    - name: Stop web deployment
      ansible.builtin.command: 'oc scale deployment {{web_deployment}} --replicas=0'
      register: scale_web_deployment_info
    - debug: 
        msg: "{{scale_web_deployment_info}}"
    
    # Start web deployment
    - name: Start web deployment
      ansible.builtin.command: 'oc scale deployment {{web_deployment}} --replicas=1'
      register: scale_web_deployment_info
    - debug: 
        msg: "{{scale_web_deployment_info}}"